### ISSUE TITLE
minor Python 3 syntax errors

### ISSUE THREAD

**Issue by fredhope2000** [Toblerity/keytree#1]
This project has the following syntax errors that prevent it from running in Python3:

- https://github.com/Toblerity/keytree/blob/db7dc932af92d4367bdb934632327c6d9963c2cb/keytree/kml.py#L92 `ValueError, "Invalid dimensions"` should be `ValueError("Invalid dimensions")`
- https://github.com/Toblerity/keytree/blob/db7dc932af92d4367bdb934632327c6d9963c2cb/keytree/__init__.py#L2-L3 `from factory` and `from kml` should be `from keytree.factory` and `from keytree.kml` respectively

I have forked the repository and made the changes, and my fork seems to be running fine in Python 3--it was just these minor syntax errors. I'm happy to contribute the fixes back to the main project and delete my fork, I just don't have the write privileges to do so.

@sgillies

**Comment by sgillies** [comment]
@fredhope2000 a pull request (to this repo, from your own fork) doesn't require write privileges, can you try that?

**Comment by fredhope2000** [comment]
@sgillies good idea! Didn't think about that. https://github.com/Toblerity/keytree/pull/2

**Comment by sgillies** [comment]
Resolved by #2
