### ISSUE TITLE
Feature request: support Google extension feature types

### ISSUE THREAD

**Issue by dericke** [Toblerity/keytree#5]
Some pro-bono work I'm doing has me converting features like [`gx:Track`](https://developers.google.com/kml/documentation/kmlreference#gx:track) into LineStrings for geojson output. I'm already writing the code to do so and would be happy to make it into a PR for this project, but I wanted to check if the interest is there before I write and submit it.

**Comment by sgillies** [comment]
@dericke I don't use this package anymore but I wouldn't mind reviewing a solid PR and making new releases from time to time. I see that one of your PRs is Python 3 only. That's fine, but I should probably make a 1.1.0 release that warns about Python 2 support going away in keytree 2.0.
